# Remova a linha 'version: 3.8' - o Docker Compose moderno não precisa dela
# e ela pode gerar um aviso.

services:
  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db # Referencia o volume nomeado aqui

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  api:
    build:
      context: .
    container_name: logscope-api
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
      - rabbitmq
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/logscope
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: 645ce38865e11b509c8fa7cd4c1856a8

# --- Definição dos volumes nomeados aqui, no mesmo nível de 'services' ---
volumes:
  mongo_data:
  # Você pode adicionar opções aqui se precisar, como 'driver: local'
  # mas para a maioria dos casos, apenas o nome já é suficiente.